### ISSUE TITLE
TypeError: Cannot set property 'onRunComplete' of undefined

### ISSUE THREAD

**Issue by callofktulu** [no23reason/jest-trx-results-processor#118]
Although the test suite passes and the trx file is created successfully, npm gives the following error and makes the pipeline fail:

`Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        7.523s, estimated 8s
Ran all test suites.
DONE
TRX file output to 'test-results.trx'
TypeError: Cannot set property 'onRunComplete' of undefined
    at TrxReporter (C:\Repo\SystemTestsSolution\node_modules\jest-trx-results-processor\dist\index.js:26:28)
    at Object.<anonymous> (C:\Repo\SystemTestsSolution\jestTrxProcessor.js:3:17)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)`

**Comment by callofktulu** [comment]
Issue is gone as I moved to reporters API.
