### ISSUE TITLE
Crash on non-existing folder for output file

### ISSUE THREAD

**Issue by mika76** [no23reason/jest-trx-results-processor#89]
**config**
```js
    reporters: [
        'default',
        [
            'jest-trx-results-processor',
            {
                outputFile: 'test_results/resulting.trx', // defaults to "test-results.trx"
                // "defaultUserName": "user name to use if automatic detection fails" // defaults to "anonymous"
            },
        ],
    ],
```

**result**
```
Error: ENOENT: no such file or directory, open 'test_results/resulting.trx'
    at Object.openSync (fs.js:439:3)
    at Object.writeFileSync (fs.js:1190:35)
    at TrxReporter.onRunComplete (.../node_modules/jest-trx-results-processor/dist/index.js:15:18)
    at .../node_modules/jest/node_modules/jest-cli/build/ReporterDispatcher.js:89:27
    at Generator.next (<anonymous>)
    at step (.../node_modules/jest/node_modules/jest-cli/build/ReporterDispatcher.js:13:30)
    at .../node_modules/jest/node_modules/jest-cli/build/ReporterDispatcher.js:24:15
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

If I create the folder manually before running it works fine.

**Comment by no23reason** [comment]
Thank you for the bug report, this should be easy to fix, I'll take a look as soon as I can.

**Comment by mika76** [comment]
Brilliant thanks!
